### ISSUE TITLE
"Invalid node object type" with Regexp

### ISSUE THREAD

**Issue by SimonDegraeve** [hapipal/confidence#22]
Hi, 

I use Confidence to build my [webpack](http://webpack.github.io/docs/configuration.html) configuration. So I need to use a Regexp in the "loaders" part of webpack configuration but this is throwing an error.

Any suggestion how I can use Regexp? And why they are forbidden in Confidence?

Thanks

**Comment by taddei** [comment]
ho about something like this?

    var store = new Confidence.Store({
        webpack: {
            $filter: 'env',
            production: {
                entry: constants.src.js,
                output:  {
                    path:     constants.dest.js.prod,
                    filename: '[name].js' // Template based on keys in entry above
                },
                module: {
                    loaders: [{
                        test: /\.jsx$/,
                        loader: 'jsx-loader'
                    }]
                }
            },
            $default: {
                watch:   true,
                entry:   constants.src.js,
                output:  {
                    path:     constants.dest.js.dev,
                    filename: '[name].js' // Template based on keys in entry above
                },
                module:  {
                    loaders: [{
                        test:   /\.jsx$/,
                        loader: 'jsx-loader'
                    },
                    {
                        test:   /\.css/,
                        loader: 'css-loader'
                    }]
                }
            }
        }
    });

**Comment by prashaantt** [comment]
I'm also trying to create a Webpack plugin, and need to pass a Webpack config object to it that uses the `test` RegExp property:

```js

// webpack.config.js

module.exports = {
    module: {
      loaders: [{
        test: /\.jsx?/,
        loaders: ['babel'],
        presets: ['react', 'es2015']
      }]
    }
};
```

```js
// manifest.js
// using the latest Glue syntax

const manifest = {
    registrations: [
        {
            plugin: {
                register: './my-plugin',
                options: {
                    config: require('./webpack.config.js')
                }
            }
        }
    ]
};
```

Confidence 1.4.2 throws me this error:

```js
Error: Invalid node object type
    at error (/Users/user/project/node_modules/confidence/lib/store.js:211:22)
```

**Comment by danielbayerlein** [comment]
@patrickkettner I have the same problem as @prashaantt. Any idea?

**Comment by patrickkettner** [comment]
@danielbayerlein have you tried the [above workaround?](https://github.com/hapijs/confidence/issues/22#issuecomment-52015122)

**Comment by danielbayerlein** [comment]
@patrickkettner This solution / workaround has many side effects... 😟

**Comment by danielbayerlein** [comment]
@patrickkettner The workaround does not work well with webpack v2.1.0-beta because the webpack default configuration used RegEx. See https://github.com/webpack/webpack/blob/6b0c20a53ad7b04d4282a8a5c334ea0982fd364c/lib/WebpackOptionsDefaulter.js#L25

**Comment by danielbayerlein** [comment]
@patrickkettner Can we add a support for RegEx?

**Comment by patrickkettner** [comment]
@hueniverse do you recall the original reason for [marking regexp as an invalid type?](https://github.com/hapijs/confidence/commit/11c782b835ac58f9b236a0abfd76e449f14fd182)

**Comment by hueniverse** [comment]
No idea.

**Comment by damusix** [comment]
Any fix for this? still getting it

**Comment by orditeck** [comment]
I have the same issue.

```js
{
    plugin: 'hapi-pagination',
    options: {
        meta: {
            location: 'body'
        },
        reply: {
            paginate: 'hapiPaginate'
        },
        routes: {
            exclude: [
                new RegExp('/documentation*'), // or /\/documentation*/,
                new RegExp('/swaggerui*') // or /\/swaggerui*/,
            ]
        }
    }
}
```
