### ISSUE TITLE
Remove module from hapi.js organization

### ISSUE THREAD

**Issue by hueniverse** [hapipal/confidence#90]
This module doesn't really fit in with the purpose of the org. It was added here because it was developed by the same original team as hapi.

@augnin if you are still interested in maintaining it, I can transfer it to your account or another org.

**Comment by devinivy** [comment]
We might consider incorporating it into the @hapipal org if @augnin is interested.  We use it in our boilerplate, which is essentially our "core."  I will have to consult some others before being able to move forward with that, if there's any interest.

**Comment by hueniverse** [comment]
Works for me if you guys work it out.

**Comment by augnin** [comment]
@hueniverse, @devinivy has confirmed that we can move confidence to @hapipal org.

**Comment by augnin** [comment]
@devinivy - now that confidence has moved to @hapipal, what's your view on License?

**Comment by devinivy** [comment]
I think that the license should stay as-is for the time being.  In order to change it I believe we would need consent from those who contributed under the current license, and I don't see any major benefit since MIT and BSD are quite similar.
