### ISSUE TITLE
Drop support for node v10 and below

### ISSUE THREAD

**Issue by devinivy** [hapipal/confidence#99]
Now that we're all tested on node v14, it's time to look ahead.

As part of this work, we should also update `@hapi/*` dependencies that were stuck on old versions due to our support of old node versions.

**Comment by devinivy** [comment]
@augnin we're planning on landing this work and then releasing v5.  If you see an issue with that just give a shout and we will adjust! :)

**Comment by Nargonath** [comment]
I'm working on this issue.

**Comment by Nargonath** [comment]
I believe there is nothing left blocking the release once the above PR is merged, isn't it?

**Comment by devinivy** [comment]
That is also as I see it 👍
